name: Update Infrastructure

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd kevin-deployment
            git pull origin main
            
            docker compose up -d --remove-orphans

            echo "Waiting for container to initialize..."
            sleep 10

            echo "ðŸ”§ Fixing Permissions & Directories..."

            docker compose exec -T kevin-app mkdir -p /var/www/resources/views
            docker compose exec -T kevin-app mkdir -p /var/www/storage/framework/{views,cache,sessions}

            docker compose exec -T kevin-app chown -R www-data:www-data /var/www/resources/views /var/www/storage
            docker compose exec -T kevin-app chmod -R 775 /var/www/resources/views /var/www/storage

            echo "ðŸ§¹ Clearing Cache..."
            docker compose exec -T kevin-app php artisan optimize:clear

            echo "Restarting Helpers..."
            docker compose restart queue-worker scheduler kevin-nginx

            docker image prune -f
            